server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO

---
spring:
  profiles: server
  
  rsocket:
    server:
      transport: tcp
      port: 7002

---
spring:
  profiles: gateway-client-1
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 3
          service-name: pong
          tags:
            INSTANCE_NAME: pong3
          broker:
            host: localhost
            port: 7002

---
spring:
  profiles: pong4
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 4
          service-name: pong
          tags:
            INSTANCE_NAME: pong4
            
---
spring:
  profiles: gateway-client-2
  cloud.gateway.rsocket.client:
    broker:
      host: localhost
      port: 7003
