server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO

---
spring:
  profiles: server
  
  rsocket:
    server:
      transport: tcp
      port: 7002

---
spring:
  profiles: pong-instance-1
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 3
          service-name: pong
          tags:
            INSTANCE_NAME: pong1

---
spring:
  profiles: pong-instance-2
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 4
          service-name: pong
          tags:
            INSTANCE_NAME: pong2

---
spring:
  profiles: gateway-instance-1
  cloud:
    gateway:
      rsocket:
        client:
          broker:
            host: localhost
            port: 7002
            
---
spring:
  profiles: gateway-instance-2
  cloud:
    gateway:
      rsocket:
        client:
          broker:
            host: localhost
            port: 7003
