server:
  port: 0

spring:
  cloud:
    gateway:
      rsocket:
        client:
          service-name: ping
---
spring:
  profiles: gateway-instance-1
  
  cloud:
    gateway:
      rsocket:
        client:
          broker:
            host: localhost
            port: 7002
---
spring:
  profiles: gateway-instance-2
  
  cloud:
    gateway:
      rsocket:
        client:
          broker:
            host: localhost
            port: 7003

--- 
spring:
  profiles: ping-instance-1
  
  cloud:
    gateway:
      rsocket:
        client:
          route-id: 1
          tags:
            INSTANCE_NAME: ping1
          forwarding:
            pong-rc:
              service_name: pong            
---
spring:
  profiles: ping-instance-2

  cloud:
    gateway:
      rsocket:
        client:
          route-id: 2
          tags:
            INSTANCE_NAME: ping2
ping:
  request-type: request_response